const http = require('node:http');
const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');

const root = __dirname, uploads = path.join(root, 'uploads');
const port = Number(process.env.PORT || 3000), MAX_FILE_SIZE = 10 * 1024 * 1024;
fs.mkdirSync(uploads, { recursive: true });
function db(op, args = {}) {
  const result = spawnSync('python3', [path.join(root, 'db.py')], { input: JSON.stringify({ op, args }), encoding: 'utf8', env: process.env });
  if (result.status !== 0) throw new Error(result.stderr || 'Database operation failed');
  return JSON.parse(result.stdout || 'null');
}
function send(res, status, body, headers = {}) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', ...headers }); res.end(JSON.stringify(body)); }
function text(res, status, body, type = 'text/plain; charset=utf-8') { res.writeHead(status, { 'content-type': type }); res.end(body); }
function readBody(req, limit = MAX_FILE_SIZE + 64 * 1024) { return new Promise((resolve, reject) => { let size=0, chunks=[]; req.on('data', c => { size += c.length; if(size > limit) { reject(new Error('Request too large')); req.destroy(); } else chunks.push(c); }); req.on('end', () => resolve(Buffer.concat(chunks))); req.on('error', reject); }); }
function parseMultipart(body, contentType) { const m = /boundary=([^;]+)/i.exec(contentType); if (!m) return null; const boundary = `--${m[1].replaceAll('"','')}`; const parts = body.toString('latin1').split(boundary); for (const part of parts) { const start = part.indexOf('\r\n\r\n'); if (start < 0) continue; const headers = part.slice(0,start), name = /name="([^"]+)"/.exec(headers)?.[1], file = /filename="([^"]*)"/.exec(headers)?.[1]; if (name === 'resume' && file) return { filename: path.basename(file), mime: /content-type:\s*([^\r\n]+)/i.exec(headers)?.[1] || 'application/octet-stream', data: Buffer.from(part.slice(start+4, -2), 'latin1') }; } return null; }
function publicUrl(filename) { const base = (process.env.PUBLIC_FILE_BASE || process.env.RENDER_EXTERNAL_URL || '').replace(/\/+$/, ''); return base ? `${base}/files/${encodeURIComponent(filename)}` : `/files/${encodeURIComponent(filename)}`; }
function isUrl(value) { try { const u=new URL(value); return u.protocol === 'http:' || u.protocol === 'https:'; } catch { return false; } }
const resultSchema = { type:'object', required:['event_id','overallScore','skillsDetected','experience','education','missingInformation','strengths','improvementSuggestions'], properties:{ event_id:{type:'string',example:'event_32619ea0db73'}, overallScore:{type:'number',minimum:0,maximum:100,example:87}, skillsDetected:{type:'array',items:{type:'string'}}, experience:{type:'object',required:['summary','years'],properties:{summary:{type:'string'},years:{type:'number'}}}, education:{type:'array',items:{type:'string'}}, missingInformation:{type:'array',items:{type:'string'}}, strengths:{type:'array',items:{type:'string'}}, improvementSuggestions:{type:'array',items:{type:'string'}} } };
const openapi = { openapi:'3.0.3', info:{title:'Resume Analyzer Callback API',version:'1.0.0',description:'Send a completed resume analysis after handling an Atenxion trigger.'}, servers:[{url: process.env.PUBLIC_ORIGIN || process.env.RENDER_EXTERNAL_URL || 'https://your-production-domain.example'}], paths:{'/api/analysis/result':{post:{summary:'Store a completed resume analysis',requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/AnalysisResult'},example:{event_id:'event_32619ea0db73',overallScore:87,skillsDetected:['Python','FastAPI'],experience:{summary:'4 years of backend development experience',years:4},education:['Bachelor of Computer Science'],missingInformation:['AWS experience is not clearly mentioned'],strengths:['Strong Python backend experience'],improvementSuggestions:['Add measurable results to project descriptions']}}}},responses:{'200':{description:'Analysis stored'},'400':{description:'Invalid callback payload'},'404':{description:'Unknown event ID'}}}}}, components:{schemas:{AnalysisResult:resultSchema}} };

const server = http.createServer(async (req,res) => { try {
  const url = new URL(req.url, `http://${req.headers.host}`), pathname = decodeURIComponent(url.pathname);
  if (req.method === 'GET' && pathname === '/health') return send(res,200,{success:true,status:'ok'});
  if (req.method === 'GET' && pathname === '/api/openapi.json') return send(res,200,openapi);
  if (req.method === 'GET' && pathname.startsWith('/files/')) { const filename=path.basename(pathname.slice(7)); const file=path.join(uploads,filename); if (!fs.existsSync(file)) return send(res,404,{success:false,error:'File not found'}); res.writeHead(200, {'content-type': filename.endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}); return fs.createReadStream(file).pipe(res); }
  if (req.method === 'POST' && pathname === '/api/resumes') { const item=parseMultipart(await readBody(req), req.headers['content-type'] || ''); if (!item) return send(res,400,{success:false,error:'A resume file is required.'}); const ext=path.extname(item.filename).toLowerCase(); if (!['.pdf','.docx'].includes(ext)) return send(res,400,{success:false,error:'Only PDF and DOCX files are supported.'}); if (item.data.length > MAX_FILE_SIZE) return send(res,400,{success:false,error:'Resume files must be 10 MB or smaller.'}); const id=`resume_${crypto.randomUUID().replaceAll('-','').slice(0,16)}`, stored=`${crypto.randomUUID()}${ext}`; await fsp.writeFile(path.join(uploads,stored),item.data); db('create_resume',{id,filename:item.filename,storedFilename:stored,mimeType:item.mime}); return send(res,201,{success:true,data:{id,filename:item.filename,url:publicUrl(stored)}}); }
  if (req.method === 'DELETE' && /^\/api\/resumes\/[^/]+$/.test(pathname)) { const item=db('delete_resume',{id:pathname.split('/').pop()}); if(!item) return send(res,404,{success:false,error:'Resume not found'}); await fsp.unlink(path.join(uploads,item.stored_filename)).catch(()=>{}); return send(res,200,{success:true}); }
  if (req.method === 'POST' && pathname === '/api/analyze') { let body; try { body=JSON.parse((await readBody(req,1024*1024)).toString()); } catch { return send(res,400,{success:false,error:'Invalid JSON request.'}); } const {resumeId,jobDescription,atenxionUrl,atenxionToken}=body; const resume=resumeId && db('get_resume',{id:resumeId}); if(!resume) return send(res,400,{success:false,error:'Please upload a resume.'}); if(typeof jobDescription !== 'string' || !jobDescription.trim()) return send(res,400,{success:false,error:'Please enter a job description.'}); const normalized=typeof atenxionUrl==='string' ? atenxionUrl.replace(/\/+$/,'') : ''; if(!isUrl(normalized)) return send(res,400,{success:false,error:'Please provide a valid Atenxion URL.'}); if(typeof atenxionToken !== 'string' || !atenxionToken.trim()) return send(res,400,{success:false,error:'Please configure the Atenxion URL and token first.'}); const eventId=`event_${crypto.randomUUID().replaceAll('-','').slice(0,16)}`; db('create_analysis',{id:crypto.randomUUID(),eventId,resumeFilename:resume.filename,resumeFile:resume.stored_filename,jobDescription:jobDescription.trim(),atenxionUrl:normalized}); let external; try { external=await fetch(`${normalized}/api/trigger/agent-trigger`,{method:'POST',headers:{Authorization:atenxionToken,'Content-Type':'application/json'},body:JSON.stringify({event_id:eventId,jobDescription:jobDescription.trim(),attachments:[publicUrl(resume.stored_filename)]}),signal:AbortSignal.timeout(20000)}); } catch { db('set_status',{eventId,status:'failed'}); return send(res,502,{success:false,error:"We couldn't start the analysis. Please check your Atenxion configuration and try again."}); } if(!external.ok) { db('set_status',{eventId,status:'failed'}); return send(res,502,{success:false,error:"We couldn't start the analysis. Please check your Atenxion configuration and try again."}); } db('set_status',{eventId,status:'analyzing'}); return send(res,202,{success:true,data:{event_id:eventId,status:'analyzing'}}); }
  if (req.method === 'GET' && /^\/api\/analysis\/[^/]+$/.test(pathname)) { const analysis=db('get_analysis',{eventId:pathname.split('/').pop()}); if(!analysis) return send(res,404,{success:false,error:'Analysis not found'}); const data={event_id:analysis.event_id,status:analysis.status}; if(analysis.result) data.result=JSON.parse(analysis.result); return send(res,200,{success:true,data}); }
  if (req.method === 'POST' && pathname === '/api/analysis/result') { let body; try { body=JSON.parse((await readBody(req,1024*1024)).toString()); } catch { return send(res,400,{success:false,error:'Invalid JSON payload.'}); } const required=['event_id','overallScore','skillsDetected','experience','education','missingInformation','strengths','improvementSuggestions']; const valid=required.every(k=>Object.hasOwn(body,k)) && typeof body.event_id==='string' && Number.isFinite(body.overallScore) && body.overallScore>=0 && body.overallScore<=100 && Array.isArray(body.skillsDetected) && body.experience && typeof body.experience.summary==='string' && Number.isFinite(body.experience.years) && ['education','missingInformation','strengths','improvementSuggestions'].every(k=>Array.isArray(body[k])); if(!valid) return send(res,400,{success:false,error:'Invalid callback payload.'}); const saved=db('complete_analysis',{eventId:body.event_id,result:Object.fromEntries(required.map(k=>[k,body[k]]))}); if(!saved.found) return send(res,404,{success:false,error:'Unknown event_id.'}); return send(res,200,{success:true,event_id:body.event_id,status:'completed'}); }
  if (req.method === 'GET') { let file=pathname==='/' ? path.join(root,'public','index.html') : path.join(root,'public',pathname); if (file.startsWith(path.join(root,'public')) && fs.existsSync(file) && fs.statSync(file).isFile()) return text(res,200,await fsp.readFile(file), file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.js')?'application/javascript; charset=utf-8':'text/html; charset=utf-8'); }
  return send(res,404,{success:false,error:'Not found'});
} catch (error) { console.error(error); return send(res,500,{success:false,error:'Unexpected server error.'}); } });
server.listen(port,()=>console.log(`Resume Analyzer listening on http://localhost:${port}`));
